CREATE TABLE CIU_CIUDADANOS(
	CIU_CODE int NOT NULL,
	CIU_NOMBRES varchar(50) NULL,
	CIU_APELLIDO varchar(50) NULL,
	CIU_SEXO varchar(15) NULL,
	CIU_NACIMIENTO datetime NULL,
	CIU_DOC_NRO varchar(20) NULL,
	CIU_EMAIL varchar(50) NULL,
	CIU_TEL_FIJO varchar(20) NULL,
	CIU_TEL_MOVIL varchar(20) NULL,
	CIU_HORARIO_CONT varchar(50) NULL,
	CIU_NO_LLAMAR varchar(4) NULL,
	CIU_NO_EMAIL varchar(4) NULL,
	CIU_DIR_CALLE varchar(50) NULL,
	CIU_DIR_NRO int NULL,
	CIU_DIR_PISO varchar(5) NULL,
	CIU_DIR_DPTO varchar(5) NULL,
	CIU_BARRIO varchar(50) NULL,
	CIU_LOCALIDAD varchar(50) NULL,
	CIU_PROVINCIA varchar(50) NULL,
	CIU_PAIS varchar(50) NULL,
	CIU_COD_POSTAL varchar(6) NULL,
	CIU_CGPC varchar(10) NULL,
	CIU_COORD_X float NULL,
	CIU_COORD_Y float NULL,
	CIU_TRABAJA varchar(4) NULL,
	CIU_NIVEL_ESTUDIO varchar(20) NULL,
	CIU_PROFESION varchar(50) NULL,
	CIU_ULTIMO_ACCESO datetime NULL,
	CIU_CANAL_INGRESO varchar(20) NULL,
	USE_CODE varchar(50) NULL,
	CIU_ESTADO varchar(30) NULL,
	CIU_TSTAMP datetime NULL,
	CIU_USUARIO varchar(50) NULL,
	CIU_CLAVE varchar(50) NULL,
 	CIU_TIPO_PERSONA varchar(20) NULL,
	CIU_RAZON_SOCIAL varchar(100) NULL,
	CIU_NACIONALIDAD varchar(100) NULL,
 CONSTRAINT PK_CIU_CIUDADANOS PRIMARY KEY CLUSTERED
 (
 	CIU_CODE ASC
 )
) 


CREATE TABLE CIU_HISTORIAL_CONTACTOS(
	CHI_CODE int NOT NULL,
	CIU_CODE int NOT NULL,
 	CSE_CODE int NOT NULL,
	CHI_FECHA datetime NULL,
	CHI_MOTIVO varchar(100) NULL,
	USE_CODE varchar(50) NULL,
	CHI_CANAL varchar(50) NULL,
 CONSTRAINT PK_CIU_HISTORIAL_CONTACTOS PRIMARY KEY CLUSTERED
 (
 	CHI_CODE ASC
 )
)


CREATE TABLE CIU_SESIONES(
	CSE_CODE int NOT NULL,
	CIU_CODE int NOT NULL,
	CSE_ANI varchar(15) NULL,
	CSE_TSTAMP datetime NULL,
	CSE_DURACION int NULL,
	USE_CODE varchar(50) NULL,
	CSE_NOTA varchar(500) NULL,
 	CSE_DERIVADO varchar(20) NULL,
 	CSE_CALL_ID varchar(20) NULL,
 	CSE_SKILL varchar(50) NULL,
 	CSE_ESTADO varchar(20) NULL,
 	CONSTRAINT PK_CIU_SESIONES_1 PRIMARY KEY CLUSTERED
 (
 	CSE_CODE ASC
 )
)
