<?php
include_once "presentation/selectarray.php";

class CDH_BARRIO extends CDH_SELECTARRAY 
{
	function __construct($parent) 
	{
		parent::__construct($parent);
		
                $barrios = array(
                    "GENERAL BELGRANO",
                    "DON EMILIO",
                    "ROLDAN BELISARIO",
                    "CARIBE",
                    "PARQUE CAMET",
                    "LAS MARGARITAS",
                    "SANTA ROSA DEL MAR DE PERALTA RAMOS",
                    "ALFAR",
                    "FARO NORTE",
                    "SANCHEZ FLORENCIO",
                    "LAS CANTERAS",
                    "PARQUE PALERMO",
                    "CERRITO SUR",
                    "JURAMENTO",
                    "SANTA MONICA",
                    "SANTA RITA",
                    "RIVADAVIA BERNARDINO",
                    "CORONEL DORREGO",
                    "NEWBERY JORGE",
                    "MALVINAS ARGENTINAS",
                    "VIRGEN DE LUJAN",
                    "LOS TRONCOS",
                    "SAN CARLOS",
                    "PLAZA PERALTA RAMOS",
                    "CAMET FELIX U.",
                    "ESTACION CAMET",
                    "DOS DE ABRIL",
                    "HIPODROMO",
                    "COLINA ALEGRE",
                    "PARQUE HERMOSO Y VALLE HERMOSO",
                    "GENERAL SAN MARTIN",
                    "SANTA CELINA",
                    "LOS ACANTILADOS",
                    "SAN PATRICIO",
                    "PLAYA SERENA",
                    "SAN JACINTO",
                    "QUEBRADAS DE PERALTA RAMOS",
                    "EL MARTILLO",
                    "GENERAL PUEYRREDON",
                    "DE LAS HERASJUAN GREGORIO",
                    "CAMINO A NECOCHEA",
                    "BOSQUE GRANDE",
                    "BOSQUE ALEGRE",
                    "EL GAUCHO",
                    "LAS AMERICAS",
                    "PERALTA RAMOS OESTE",
                    "EL PROGRESO",
                    "DEL PUERTO",
                    "PUNTA MOGOTES",
                    "COLINAS DE PERALTA RAMOS",
                    "CERRITO Y SAN SALVADOR",
                    "TERMAS  HUINCO",
                    "VILLA LOURDES",
                    "LAS AVENIDAS",
                    "REGIONAL",
                    "LAS LILAS",
                    "SAN JOSE",
                    "LOS ANDES",
                    "SAN CAYETANO",
                    "SARMIENTO DOMINGO FAUSTINO",
                    "NUEVE DE JULIO",
                    "ESTACION NORTE",
                    "NUEVA POMPEYA",
                    "LA PERLA",
                    "VILLA PRIMERA",
                    "PARQUE LURO",
                    "LOS PINARES",
                    "SANTA ROSA DE LIMA",
                    "SAN JORGE",
                    "AMEGHINO FLORENTINO",
                    "LIBERTAD",
                    "CONSTITUCIÓN",
                    "ZACAGNINI JOSE MANUEL",
                    "PARQUE MONTEMAR-EL GROSELLAR",
                    "LOPEZ DE GOMARA",
                    "LOS TILOS",
                    "AEROPARQUE",
                    "LA FLORIDA",
                    "ESTRADA JOSE MANUEL",
                    "PLAYA GRANDE",
                    "EL JARDIN DE PERALTA RAMOS",
                    "AUTODROMO",
                    "BOSQUE PERALTA RAMOS",
                    "PARQUE INDEPENDENCIA",
                    "EL JARDIN DE STELLA MARIS",
                    "DE LA PLAZA FORTUNATO",
                    "SAN ANTONIO",
                    "PARQUE EL CASAL",
                    "SANTA PAULA",
                    "SIERRA DE LOS PADRES",
                    "LA PEREGRINA",
                    "LA GLORIA DE LA PEREGRINA",
                    "EL BOQUERON",
                    "PLAYA LOS LOBOS",
                    "PLAYA CHAPADMALAL",
                    "ARROYO CHAPADMALAL",
                    "SAN EDUARDO DE CHAPADMALAL",
                    "EL MARQUESADO",
                    "SAN EDUARDO DEL MAR",
                    "LOMAS DE STELLA MARIS",
                    "ESTACION CHAPADMALAL",
                    "LA HERRADURA",
                    "JOSE HERNÁNDEZ",
                    "LOMAS DEL GOLF",
                    "COLONIA BARRAGAN",
                    "LA GERMANA",
                    "PARQUE INDUSTRIAL",
                    "FRAY LUIS BELTRAN",
                    "FUNES Y SAN LORENZO",
                    "PINOS DE ANCHORENA",
                    "PRIMERA JUNTA",
                    "SAN JUAN",
                    "DON BOSCO",
                    "ESTACIÓN TERMINAL",
                    "GENERAL ROCA",
                    "LEANDRO N. ALEM",
                    "EL COLMENAR",
                    "LAS RETAMAS",
                    "VILLA SERRANA",
                    "BATAN",
                    "DIVINO ROSTRO",
                    "NUEVO GOLF",
                    "LOMAS DE BATAN",
                    "AREA CENTRO" 
                );

                foreach($barrios as $n)
                    $this->m_array[$n] = $n; 
	}
}
